FROM node:14-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/frontend

# Installing dependencies
COPY package*.json .
RUN yarn install

# Copying source files
COPY . .

# Building app
# RUN yarn build
EXPOSE 3000

# Running the app
CMD ["yarn", "dev"]